N5x libloc_api_v02 cannot build from AOSP
We've satisfied the shared libraries dependencies, although
we're still missing the header includes. Try to override the
AOSP module with our own prebuilt.

```
device/lge/bullhead/location/loc_api/loc_api_v02/location_service_v02.h:78:10: fatal error: 'qmi_idl_lib.h' file not found
#include "qmi_idl_lib.h"
```

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>